# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

dotenv:
  - .env

includes:
  db:
    taskfile: taskfiles/db.yml
    dir: .
  lint:
    taskfile: taskfiles/lint.yml
    dir: .

tasks:
  test:
    desc: Run all tests
    cmd: bun test --recursive

  typecheck:
    desc: Typecheck all packages
    cmd: bun run --filter='*' typecheck

  format:
    desc: Format all files
    cmd: bun run biome check --write

  build:
    desc: Build all packages
    cmd: bun run --filter='*' build
