{{- if .Values.minio.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "circus.fullname" . }}-minio
  labels:
    {{- include "circus.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  type: {{ .Values.minio.service.type }}
  selector:
    {{- include "circus.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: minio
  ports:
    - name: api
      port: {{ .Values.minio.service.apiPort }}
      targetPort: 9000
      protocol: TCP
    - name: console
      port: {{ .Values.minio.service.consolePort }}
      targetPort: 9001
      protocol: TCP
{{- end }}
