{{- if .Values.nats.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "circus.fullname" . }}-nats
  labels:
    {{- include "circus.labels" . | nindent 4 }}
    app.kubernetes.io/component: nats
spec:
  replicas: {{ .Values.nats.replicaCount }}
  selector:
    matchLabels:
      {{- include "circus.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: nats
  template:
    metadata:
      labels:
        {{- include "circus.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: nats
    spec:
      containers:
        - name: nats
          image: "{{ .Values.nats.image.repository }}:{{ .Values.nats.image.tag }}"
          imagePullPolicy: {{ .Values.nats.image.pullPolicy }}
          ports:
            - containerPort: 4222
              name: client
              protocol: TCP
          args:
            {{- toYaml .Values.nats.args | nindent 12 }}
          {{- if .Values.nats.storage.enabled }}
          volumeMounts:
            - name: data
              mountPath: /data
          {{- end }}
      {{- if .Values.nats.storage.enabled }}
      volumes:
        - name: data
          emptyDir: {}
      {{- end }}
{{- end }}
