{{- if .Values.nats.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "circus.fullname" . }}-nats
  labels:
    {{- include "circus.labels" . | nindent 4 }}
    app.kubernetes.io/component: nats
spec:
  type: {{ .Values.nats.service.type }}
  selector:
    {{- include "circus.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nats
  ports:
    - name: client
      port: {{ .Values.nats.service.port }}
      targetPort: 4222
      protocol: TCP
{{- end }}
