{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "circus.fullname" . }}-redis
  labels:
    {{- include "circus.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: {{ .Values.redis.service.type }}
  selector:
    {{- include "circus.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: 6379
      protocol: TCP
{{- end }}
