{{- if and .Values.ringmaster.enabled .Values.ringmaster.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.ringmaster.serviceAccount.name | default (printf "%s-ringmaster" (include "circus.fullname" .)) }}
  labels:
    {{- include "circus.labels" . | nindent 4 }}
    app.kubernetes.io/component: ringmaster
{{- end }}
