apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/redis
  - ../../components/nats
  - ../../components/minio
  - ../../components/grafana
  - ../../components/loki
  - ../../components/mimir
  - ../../components/tempo

helmCharts:
  - name: opentelemetry-collector
    repo: https://open-telemetry.github.io/opentelemetry-helm-charts
    releaseName: otel-collector
    namespace: default
    valuesFile: helm/otel-collector-values.yaml
