{{- if .Values.api.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "circus.fullname" . }}-api
  labels:
    {{- include "circus.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "circus.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: api
      port: {{ .Values.api.service.port }}
      targetPort: 4773
      protocol: TCP
{{- end }}
