ringmaster:
  enabled: true
  image:
    repository: ringmaster

usher:
  enabled: true
  image:
    repository: usher

bullhorn:
  enabled: true
  image:
    repository: bullhorn

dashboard:
  enabled: true
  image:
    repository: dashboard
