ringmaster:
  enabled: true
  image:
    repository: ringmaster
  chimp:
    image: "chimp:latest"

usher:
  enabled: true
  image:
    repository: usher

bullhorn:
  enabled: false
  image:
    repository: bullhorn

ledger:
  enabled: true
  image:
    repository: ledger

dashboard:
  enabled: true
  image:
    repository: dashboard

chimp:
  brainType: opencode
  extraEnv:
    - name: ANTHROPIC_API_KEY
      valueFrom:
        secretKeyRef:
          name: anthropic-api-key
          key: ANTHROPIC_API_KEY
  initConfig:
    enabled: true
    commands:
      - command: clone-repo
        args:
          url: "https://github.com/tonyd33/circus.git"
      - command: set-working-dir
        args:
          path: "circus"
