ringmaster:
  enabled: true
  image:
    repository: ringmaster
  profileTemplate:
    base:
      auth:
        claude:
          source: env
          envVar: CLAUDE_CODE_OAUTH_TOKEN
        opencode:
          source: env
          envVar: OPENCODE_API_KEY
        opencode-go:
          source: env
          envVar: OPENCODE_GO_API_KEY
        openrouter:
          source: env
          envVar: OPENROUTER_API_KEY
      extraEnv:
        - name: CLAUDE_CODE_OAUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: circus-secrets
              key: CLAUDE_CODE_OAUTH_TOKEN
        - name: OPENCODE_GO_API_KEY
          valueFrom:
            secretKeyRef:
              name: circus-secrets
              key: OPENCODE_GO_API_KEY
        - name: OPENCODE_API_KEY
          valueFrom:
            secretKeyRef:
              name: circus-secrets
              key: OPENCODE_API_KEY
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: circus-secrets
              key: OPENROUTER_API_KEY
        - name: GITHUB_APP_ID
          value: "3434984"
        - name: GITHUB_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: circus-secrets
              key: GITHUB_PRIVATE_KEY
        - name: GITHUB_INSTALLATION_ID
          value: "125365483"

usher:
  enabled: true
  image:
    repository: usher
  routes:
    - adapter: debug
      path: /api/webhooks/debug
    - adapter: github
      path: /api/webhooks/github
    - adapter: discord
      path: /api/webhooks/discord
  extraEnv:
    - name: GITHUB_BOT_NAME
      value: circus-chimp
    - name: GITHUB_APP_ID
      value: '3434984'
    - name: GITHUB_WEBHOOK_SECRET
      valueFrom:
        secretKeyRef:
          name: circus-secrets
          key: GITHUB_WEBHOOK_SECRET
    - name: GITHUB_PRIVATE_KEY
      valueFrom:
        secretKeyRef:
          name: circus-secrets
          key: GITHUB_PRIVATE_KEY
    - name: DISCORD_PUBLIC_KEY
      value: '94f9710cabc6d6b331b92adbe21bc4e2796d331f0a754fe2ca8211bbc7db5313'
    - name: DISCORD_APPLICATION_ID
      value: '1495349106342887444'

bullhorn:
  enabled: true
  image:
    repository: bullhorn
  extraEnv:
    - name: GITHUB_APP_ID
      value: '3434984'
    - name: GITHUB_PRIVATE_KEY
      valueFrom:
        secretKeyRef:
          name: circus-secrets
          key: GITHUB_PRIVATE_KEY

dashboard:
  enabled: true
  image:
    repository: dashboard
