{{- if .Values.ringmaster.enabled -}}
{{- $extraEnv := default (list) .Values.chimp.extraEnv -}}
{{- $volumeMounts := default (list) .Values.chimp.volumeMounts -}}
{{- $volumes := default (list) .Values.chimp.volumes -}}
{{- if .Values.chimp.initConfig.enabled -}}
{{- $extraEnv = append $extraEnv (dict "name" "CHIMP_INIT_CONFIG" "value" "/etc/chimp/config.json") -}}
{{- $volumeMounts = append $volumeMounts (dict "name" "chimp-init-config" "mountPath" "/etc/chimp" "readOnly" true) -}}
{{- $volumes = append $volumes (dict "name" "chimp-init-config" "configMap" (dict "name" (printf "%s-chimp-init-config" (include "circus.fullname" .)))) -}}
{{- end -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "circus.fullname" . }}-chimp-job-config
  labels:
    {{- include "circus.labels" . | nindent 4 }}
    app.kubernetes.io/component: ringmaster
data:
  chimp-job-config.json: |
    {
      "extraEnv": {{ toJson $extraEnv }},
      "volumeMounts": {{ toJson $volumeMounts }},
      "volumes": {{ toJson $volumes }},
      "imagePullPolicy": {{ toJson (default "IfNotPresent" .Values.chimp.imagePullPolicy) }}
    }
{{- end }}
