{{- if .Values.ringmaster.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "circus.fullname" . }}-ringmaster
  labels:
    {{- include "circus.labels" . | nindent 4 }}
    app.kubernetes.io/component: ringmaster
spec:
  replicas: {{ .Values.ringmaster.replicaCount }}
  selector:
    matchLabels:
      {{- include "circus.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ringmaster
  template:
    metadata:
      labels:
        {{- include "circus.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ringmaster
    spec:
      serviceAccountName: {{ .Values.ringmaster.serviceAccount.name | default (printf "%s-ringmaster" (include "circus.fullname" .)) }}
      containers:
        - name: ringmaster
          image: "{{ .Values.ringmaster.image.repository }}:{{ .Values.ringmaster.image.tag }}"
          imagePullPolicy: {{ .Values.ringmaster.image.pullPolicy }}
          args:
            - "--profile-file"
            - "/etc/circus/ringmaster/profiles.json"
            - "--namespace"
            - "$(NAMESPACE)"
          env:
            - name: REDIS_URL
              value: {{ .Values.externalServices.redis.url | quote }}
            - name: NATS_URL
              value: {{ .Values.externalServices.nats.url | quote }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CHIMP_JOB_CONFIG_PATH
              value: "/etc/circus/chimp-job-config.json"
          volumeMounts:
            - name: chimp-job-config
              mountPath: /etc/circus
              readOnly: true
            - name: chimp-profiles
              mountPath: /etc/circus/ringmaster
              readOnly: true
          resources:
            {{- toYaml .Values.ringmaster.resources | nindent 12 }}
      volumes:
        - name: chimp-job-config
          configMap:
            name: {{ include "circus.fullname" . }}-chimp-job-config
        - name: chimp-profiles
          configMap:
            name: {{ include "circus.fullname" . }}-chimp-profiles
{{- end }}
