{{- if .Values.ringmaster.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "circus.fullname" . }}-chimp-profiles
  labels:
    {{- include "circus.labels" . | nindent 4 }}
    app.kubernetes.io/component: ringmaster
data:
  profiles.json: |
    {{ toJson .Values.chimp.profiles }}
{{- end }}
