{{- if .Values.bullhorn.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "circus.fullname" . }}-bullhorn
  labels:
    {{- include "circus.labels" . | nindent 4 }}
    app.kubernetes.io/component: bullhorn
spec:
  replicas: {{ .Values.bullhorn.replicaCount }}
  selector:
    matchLabels:
      {{- include "circus.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: bullhorn
  template:
    metadata:
      labels:
        {{- include "circus.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: bullhorn
    spec:
      containers:
        - name: bullhorn
          image: "{{ .Values.bullhorn.image.repository }}:{{ .Values.bullhorn.image.tag }}"
          imagePullPolicy: {{ .Values.bullhorn.image.pullPolicy }}
          env:
            - name: NATS_URL
              value: {{ .Values.externalServices.nats.url | quote }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: METRICS_PORT
              value: "9090"
            {{- with .Values.bullhorn.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: 9090
              protocol: TCP
          resources:
            {{- toYaml .Values.bullhorn.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 3
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /healthz
              port: 9090
            initialDelaySeconds: 0
            periodSeconds: 1
            timeoutSeconds: 5
            failureThreshold: 30
{{- end }}
